apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-user-binding
roleRef:
  kind: ClusterRole
  name: dev-user
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
