apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-user
rules:
  - apiGroups: ["*"]
    resources:
      [
        "daemonsets",
        "deployments",
        "app",
        "replicasets",
        "statefulsets",
        "configmaps",
        "pods",
        "secrets",
        "services",
        "cronjobs",
        "jobs",
        "namespaces",
        "nodes",
        "replicationcontrollers",
        "horizontalpodautoscalers",
      ]
    verbs: ["get", "list", "watch"]
    # verbs: ["get", "create", "list", "watch", "describe", "edit", "delete", "apply"]
